templates:
  - name: skeleton
    url: https://github.com/THE108/go-skeleton.git

variables:
  repoPath: stash.eyeota.com/tsuk
  useKafka: true
  types:
    - int
    - int64
    - uint64
    - string
    - float64