// Autogenerated - DO NOT EDIT
package main

import (
	"flag"
	"syscall"
	"os"
	"os/signal"
	"fmt"

	"butler{ .Vars.repoPath }/butler{ .Project.Name }/config"
	"butler{ .Vars.repoPath }/butler{ .Project.Name }/resources"
	"butler{ .Vars.repoPath }/butler{ .Project.Name }/app"
	"butler{ .Vars.repoPath }/butler{ .Project.Name }/log"
	"butler{ .Vars.repoPath }/butler{ .Project.Name }/monitoring"
)

// Variables values set during compile time (see Makefile)
var (
	// Application name
	AppName = "butler{ .Project.Name }"
	// AppVersion application version
	AppVersion string
	// GoVersion GO version that used to build application
	GoVersion string
	// BuildDate date when application is built
	BuildDate string
	// GitLog log of commit when build app
	GitLog string
)

func main() {
	var filename string
	var showVersionAndExit bool

	flag.StringVar(&filename, "config", "config.json", "config file name")
	flag.BoolVar(&showVersionAndExit, "v", false, "version")
	flag.Parse()

	if showVersionAndExit {
		fmt.Printf("%s - butler{ .Project.Description }\nversion: %s go: %s build: %s git: %s", AppName, AppVersion, GoVersion, BuildDate, GitLog)
		return
	}

	cfg, err := config.Parse(filename, AppVersion, GoVersion, BuildDate, GitLog)
	if err != nil {
		fmt.Println(err)
		return
	}

	logger, err := log.NewLogger()
	if err != nil {
		fmt.Println(err)
		return
	}

	mon := monitoring.NewMonitoring()

	res, err := resources.InitResources(cfg)
	if err != nil {
		fmt.Println(err)
		return
	}

	quitCh := make(chan struct{})

	go func() {
		defer close(quitCh)

		logger.Info("Start application")
		if err := app.Run(cfg, logger, mon, res); err != nil {
			fmt.Println(err)
		}
	}()

	ch := make(chan os.Signal, 1)
	signal.Notify(ch, syscall.SIGINT, syscall.SIGTERM)
	for {
		select {
		case s := <-ch:
			switch s {
			case syscall.SIGINT, syscall.SIGTERM:
				signal.Stop(ch)
				app.Shutdown()
				logger.Info("Shutdown application")
			}

		case <-quitCh:
			return
		}
	}
}
